version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: ["start-dev", "--import-realm"]
    env_file: .env.dev
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}  # Default 'admin'
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - identity

networks:
  identity:
